# Generated by Django 4.2.3 on 2023-07-19 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FdBkConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BU_ID', models.IntegerField(null=True)),
                ('BU_Name', models.CharField(max_length=255, null=True)),
                ('BU_Address', models.TextField(null=True)),
                ('BU_Email_Id', models.EmailField(max_length=255, null=True)),
                ('BU_Contact_Number', models.CharField(max_length=20, null=True)),
                ('BU_Logo', models.ImageField(null=True, upload_to='logos/')),
                ('BU_ColorTheme', models.CharField(max_length=20, null=True)),
                ('bu_font_color', models.CharField(max_length=20, null=True)),
                ('FdBk_Page_Title', models.TextField(null=True)),
                ('FdBk_Page_SubTitle', models.TextField(null=True)),
                ('FdBk_Page_Dialog', models.TextField(null=True)),
                ('FdBk_Page_LastNote', models.TextField(null=True)),
                ('BU_MainImg', models.CharField(max_length=20, null=True)),
                ('BU_LastImg', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FdBkQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('IsMandatory', models.CharField(max_length=30)),
                ('Score_1_Feeling', models.CharField(max_length=30)),
                ('Score_1_Symbol', models.CharField(max_length=15)),
                ('Score_1_Color', models.CharField(max_length=15)),
                ('Score_1_FollowUp_Question', models.TextField()),
                ('Score_1_Display_Message', models.TextField()),
                ('Score_2_Feeling', models.CharField(max_length=30)),
                ('Score_2_Symbol', models.CharField(max_length=15)),
                ('Score_2_Color', models.CharField(max_length=15)),
                ('Score_2_FollowUp_Question', models.TextField()),
                ('Score_2_Display_Message', models.TextField()),
                ('Score_3_Feeling', models.CharField(max_length=30)),
                ('Score_3_Symbol', models.CharField(max_length=15)),
                ('Score_3_Color', models.CharField(max_length=15)),
                ('Score_3_FollowUp_Question', models.TextField()),
                ('Score_3_Display_Message', models.TextField()),
                ('Score_4_Feeling', models.CharField(max_length=30)),
                ('Score_4_Symbol', models.CharField(max_length=15)),
                ('Score_4_Color', models.CharField(max_length=15)),
                ('Score_4_FollowUp_Question', models.TextField()),
                ('Score_4_Display_Message', models.TextField()),
                ('Score_5_Feeling', models.CharField(max_length=30)),
                ('Score_5_Symbol', models.CharField(max_length=15)),
                ('Score_5_Color', models.CharField(max_length=15)),
                ('Score_5_FollowUp_Question', models.TextField()),
                ('Score_5_Display_Message', models.TextField()),
                ('CompanyId', models.BigIntegerField()),
                ('BranchId', models.BigIntegerField()),
                ('question_type', models.CharField(max_length=20)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FbDkList.fdbkconfig')),
            ],
        ),
    ]
