# Generated by Django 4.2.4 on 2023-08-08 19:24

import FbDkList.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FdBkConfig',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('BU_ID', models.IntegerField(null=True)),
                ('BU_Name', models.CharField(max_length=255, null=True)),
                ('BU_Address', models.TextField(null=True)),
                ('BU_Email_Id', models.EmailField(max_length=255, null=True)),
                ('BU_Contact_Number', models.CharField(max_length=20, null=True)),
                ('BU_Logo', models.ImageField(null=True, upload_to=FbDkList.models.FdBkConfig.logo_upload_path)),
                ('BU_ColorTheme', models.CharField(max_length=20, null=True)),
                ('bu_font_color', models.CharField(max_length=20, null=True)),
                ('FdBk_Page_Title', models.TextField(null=True)),
                ('FdBk_Page_SubTitle', models.TextField(null=True)),
                ('FdBk_Page_Dialog', models.TextField(null=True)),
                ('FdBk_Page_LastNote', models.TextField(null=True)),
                ('BU_MainImg', models.CharField(max_length=20, null=True)),
                ('BU_LastImg', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FdBkQuestions',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.TextField()),
                ('IsMandatory', models.CharField(max_length=30)),
                ('Score_1_Feeling', models.CharField(max_length=30)),
                ('Score_1_Symbol', models.CharField(max_length=15)),
                ('Score_1_Color', models.CharField(max_length=15)),
                ('Score_1_FollowUp_Question', models.TextField()),
                ('Score_1_Display_Message', models.TextField()),
                ('Score_2_Feeling', models.CharField(max_length=30)),
                ('Score_2_Symbol', models.CharField(max_length=15)),
                ('Score_2_Color', models.CharField(max_length=15)),
                ('Score_2_FollowUp_Question', models.TextField()),
                ('Score_2_Display_Message', models.TextField()),
                ('Score_3_Feeling', models.CharField(max_length=30)),
                ('Score_3_Symbol', models.CharField(max_length=15)),
                ('Score_3_Color', models.CharField(max_length=15)),
                ('Score_3_FollowUp_Question', models.TextField()),
                ('Score_3_Display_Message', models.TextField()),
                ('Score_4_Feeling', models.CharField(max_length=30)),
                ('Score_4_Symbol', models.CharField(max_length=15)),
                ('Score_4_Color', models.CharField(max_length=15)),
                ('Score_4_FollowUp_Question', models.TextField()),
                ('Score_4_Display_Message', models.TextField()),
                ('Score_5_Feeling', models.CharField(max_length=30)),
                ('Score_5_Symbol', models.CharField(max_length=15)),
                ('Score_5_Color', models.CharField(max_length=15)),
                ('Score_5_FollowUp_Question', models.TextField()),
                ('Score_5_Display_Message', models.TextField()),
                ('BranchId', models.BigIntegerField(blank=True, null=True)),
                ('question_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TOrdHead',
            fields=[
                ('TOrdNo', models.CharField(max_length=20)),
                ('TOrdDate', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feedback_completed', models.BooleanField(default=False)),
                ('order_avg_rating', models.FloatField(default=0.0)),
                ('Address', models.CharField(blank=True, max_length=500, null=True)),
                ('Avg_Rating', models.FloatField(default=0.0)),
                ('OverAll_Comment', models.CharField(blank=True, max_length=900, null=True)),
                ('BranchId', models.IntegerField(blank=True, null=True)),
                ('TOrdHdID', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('TrackID', models.CharField(blank=True, max_length=50, null=True)),
                ('CompanyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_company', to='FbDkList.fdbkconfig')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='FbDkList.fdbkconfig')),
                ('questions', models.ManyToManyField(to='FbDkList.fdbkquestions')),
            ],
        ),
        migrations.CreateModel(
            name='FdBk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField(blank=True, null=True)),
                ('Rating', models.IntegerField()),
                ('Comment', models.TextField(blank=True, null=True)),
                ('CompanyId', models.IntegerField(blank=True, null=True)),
                ('BranchId', models.IntegerField(blank=True, null=True)),
                ('OrderUId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='FbDkList.tordhead')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FbDkList.fdbkquestions')),
            ],
        ),
    ]
