# Generated by Django 4.2.3 on 2023-07-19 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FbDkList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fdbkquestions',
            name='BranchId',
        ),
        migrations.RemoveField(
            model_name='fdbkquestions',
            name='CompanyId',
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Question', models.TextField()),
                ('Rating', models.IntegerField()),
                ('Comment', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FbDkList.fdbkquestions')),
            ],
        ),
    ]
