# Generated by Django 4.2.3 on 2023-07-20 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FbDkList', '0002_remove_fdbkquestions_branchid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fdbkquestions',
            name='business',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Id',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20)),
                ('order_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='FbDkList.fdbkconfig')),
            ],
        ),
        migrations.AddField(
            model_name='fdbkquestions',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FbDkList.order'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
