# Generated by Django 4.2.3 on 2023-07-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FbDkList', '0003_remove_fdbkquestions_business_remove_feedback_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fdbkquestions',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='questions',
            field=models.ManyToManyField(to='FbDkList.fdbkquestions'),
        ),
    ]
