# Generated by Django 4.2.3 on 2023-07-28 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FbDkList', '0004_remove_fdbkquestions_order_order_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='Question',
        ),
        migrations.AddField(
            model_name='feedback',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FbDkList.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='feedback_completed',
            field=models.BooleanField(default=False),
        ),
    ]
