# Generated by Django 4.2.3 on 2023-07-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FbDkList', '0004_remove_fdbkquestions_order_order_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdbkquestions',
            name='question_type',
            field=models.CharField(choices=[('stars', 'Stars'), ('hearts', 'Hearts'), ('emoji', 'Emoji')], default='stars', max_length=20),
        ),
    ]
