# Generated by Django 4.2.3 on 2023-07-29 09:09

import FbDkList.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FbDkList', '0005_remove_feedback_question_feedback_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdbkconfig',
            name='BU_Logo',
            field=models.ImageField(null=True, upload_to=FbDkList.models.FdBkConfig.logo_upload_path),
        ),
    ]
