# Generated by Django 4.2.3 on 2023-08-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FbDkList', '0006_alter_fdbkconfig_bu_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_avg_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
