# Generated by Django 4.2.4 on 2023-08-07 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FbDkList', '0008_alter_feedback_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FdBk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField(blank=True, null=True)),
                ('Rating', models.IntegerField()),
                ('Comment', models.TextField(blank=True, null=True)),
                ('CompanyId', models.IntegerField(blank=True, null=True)),
                ('BranchId', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TOrdHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TOrdNo', models.CharField(max_length=20)),
                ('TOrdDate', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feedback_completed', models.BooleanField(default=False)),
                ('order_avg_rating', models.FloatField(default=0.0)),
                ('Address', models.CharField(blank=True, max_length=500, null=True)),
                ('Avg_Rating', models.FloatField(default=0.0)),
                ('OverAll_Comment', models.CharField(blank=True, max_length=900, null=True)),
                ('BranchId', models.IntegerField(blank=True, null=True)),
                ('CompanyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_company', to='FbDkList.fdbkconfig')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='FbDkList.fdbkconfig')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='business',
        ),
        migrations.RemoveField(
            model_name='order',
            name='questions',
        ),
        migrations.AddField(
            model_name='fdbkquestions',
            name='BranchId',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='tordhead',
            name='questions',
            field=models.ManyToManyField(to='FbDkList.fdbkquestions'),
        ),
        migrations.AddField(
            model_name='fdbk',
            name='OrderUId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacksUids', to='FbDkList.tordhead'),
        ),
        migrations.AddField(
            model_name='fdbk',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='FbDkList.tordhead'),
        ),
        migrations.AddField(
            model_name='fdbk',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FbDkList.fdbkquestions'),
        ),
    ]
