# Generated by Django 4.2.4 on 2023-08-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FbDkList', '0009_fdbk_tordhead_remove_order_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tordhead',
            name='id',
        ),
        migrations.AddField(
            model_name='tordhead',
            name='TOrdHdID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
